version: "3.9"

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    networks:
      macvlan_net:
        ipv4_address: 192.168.178.121
    volumes:
      - ${APP_DATA_DIR}/data/npm-data:/data
      - ${APP_DATA_DIR}/data/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

networks:
  macvlan_net:
    external: true
