version: "3.7"

services:
  app_proxy:
    environment:
      # App host + port leiten Requests Ã¼ber Umbrel Proxy
      APP_HOST: punk_faster-whisper_1
      APP_PORT: 10300

  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=small-int8
      - LOCAL_ONLY= #optional
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=de #optional
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: unless-stopped
